// app/page.tsx
import Link from "next/link";
import { getChallengeBySlug, loadChallenges } from "@/lib/challenges/loader";
import CodeBlock from "@/components/challenge/CodeBlock";
import LandingHeroSample from "@/components/landing/LandingHeroSample";
import { Ghost, Bug, ShieldAlert, Shuffle, Zap, Puzzle, Package } from "lucide-react";
import { Category } from "@/lib/challenges/types";

export const metadata = {
  title: "ReviewLabs — Practice Catching AI Code Bugs",
  description: "Improve your code review heuristics. Bite-sized interactive challenges to catch bugs, security issues, and hallucinated APIs generated by LLMs.",
};

const categoryInfos = [
  {
    id: "hallucinated-apis" as Category,
    title: "Hallucinated APIs",
    description: "LLMs invent modules, library arguments, or library functions that look real but don't exist.",
    icon: Ghost,
    color: "text-[#391c57] bg-[#d6b6f6]/25 border-[#d6b6f6]/50",
  },
  {
    id: "logic-errors" as Category,
    title: "Logic Errors",
    description: "Incorrect boundaries, index offsets, pagination calculations, or missing edge cases.",
    icon: Bug,
    color: "text-[#2a9d99] bg-[#2a9d99]/8 border-[#2a9d99]/20",
  },
  {
    id: "security" as Category,
    title: "Security",
    description: "OS command injection, SQL injection, path traversal, or leaked credentials directly written into code.",
    icon: ShieldAlert,
    color: "text-danger-text bg-danger-subtle border-[#dc2626]/20",
  },
  {
    id: "race-conditions" as Category,
    title: "Race Conditions",
    description: "Stale React state closures, asynchronous listener leaks, or parallel request conditions.",
    icon: Shuffle,
    color: "text-[#793400] bg-[#dd5b00]/8 border-[#dd5b00]/20",
  },
  {
    id: "performance" as Category,
    title: "Performance",
    description: "N+1 query problems, heavy calculations running on render cycles, or database connection exhaustion.",
    icon: Zap,
    color: "text-success-text bg-success-subtle border-[#1aae39]/20",
  },
  {
    id: "wrong-patterns" as Category,
    title: "Wrong Patterns",
    description: "Silent failure handlers, anti-patterns, typing escapes, or incorrect React prop drilling patterns.",
    icon: Puzzle,
    color: "text-[#523410] bg-[#523410]/6 border-[#523410]/15",
  },
  {
    id: "dependencies" as Category,
    title: "Dependencies",
    description: "SSR window clashes, library version mismatch configurations, or incorrect peer configurations.",
    icon: Package,
    color: "text-txt-tertiary bg-black/[0.04] border-border-subt",
  },
];

export default async function Home() {
  const challenges = loadChallenges();

  // Use the phantom module as our default sample challenge, or fallback to the first loaded challenge
  const sampleChallenge = getChallengeBySlug("the-phantom-module") || challenges[0];

  const codeBlockElement = sampleChallenge ? (
    <CodeBlock
      code={sampleChallenge.code.snippet}
      language={sampleChallenge.code.language}
      filename={sampleChallenge.code.filename}
      buggyText={sampleChallenge.explanation.theFix.before}
      subtle={true} // Subtly indicates the buggy line from the start
    />
  ) : null;

  return (
    <div className="w-full flex flex-col items-center">
      {/* 1. Hero Section */}
      <section className="w-full relative py-24 px-6 flex flex-col items-center text-center space-y-8 select-none">
        <span className="text-[10px] font-sans font-medium tracking-widest text-txt-secondary uppercase bg-surface border border-border-subt px-4 py-1.5 rounded-full">
          A Free Interactive Platform by @satyatechgeek
        </span>

        <h1 className="font-display text-5xl sm:text-7xl md:text-8xl text-txt-primary max-w-4xl pt-4">
          AI writes the code. <br className="hidden sm:inline" />
          <span className="text-txt-primary">You review it.</span>
        </h1>

        <p className="text-base sm:text-lg text-txt-secondary max-w-lg leading-relaxed font-sans-humanist tracking-wide">
          Interactive challenges for catching the bugs that Copilot, Cursor, and Claude Code sneak into your pull requests.
        </p>

        <div className="flex flex-col sm:flex-row items-center gap-4 w-full sm:w-auto pt-6 select-none">
          <Link
            href="/challenges"
            className="w-full sm:w-auto text-center px-6 h-11 flex items-center justify-center rounded-full text-sm font-sans font-semibold bg-accent hover:bg-accent-hover text-txt-inverse transition-colors [box-shadow:var(--shadow-soft)] active:scale-95 cursor-pointer"
          >
            Start Practicing
          </Link>
          <Link
            href="/mock-interview"
            className="w-full sm:w-auto text-center px-6 h-11 flex items-center justify-center rounded-full text-sm font-sans font-semibold bg-surface hover:bg-surface-elevated text-txt-primary border border-border-subt transition-all active:scale-95 cursor-pointer [box-shadow:var(--shadow-soft)]"
          >
            Try Mock Interview
          </Link>
        </div>
      </section>

      {/* 2. Interactive Sample Challenge */}
      {sampleChallenge && codeBlockElement && (
        <section className="w-full relative py-16 px-6 border-t border-border-subt bg-canvas">
          <div className="max-w-3xl mx-auto">
            <LandingHeroSample
              challenge={sampleChallenge}
              codeBlock={codeBlockElement}
            />
          </div>
        </section>
      )}

      {/* 3. Stats Row (Minimal Print-style Layout) */}
      <section className="w-full border-y border-border-subt bg-surface-card py-10 select-none">
        <div className="max-w-4xl mx-auto px-6 grid grid-cols-3 text-center divide-x divide-border-subt">
          <div className="space-y-1.5">
            <p className="text-3xl md:text-4xl font-sans font-bold text-txt-primary tracking-tight font-sans-humanist">
              {challenges.length}
            </p>
            <p className="text-[10px] font-sans font-bold text-txt-tertiary uppercase tracking-widest">
              Challenges
            </p>
          </div>
          <div className="space-y-1.5">
            <p className="text-3xl md:text-4xl font-sans font-bold text-txt-primary tracking-tight font-sans-humanist">
              {categoryInfos.length}
            </p>
            <p className="text-[10px] font-sans font-bold text-txt-tertiary uppercase tracking-widest">
              Categories
            </p>
          </div>
          <div className="space-y-1.5">
            <p className="text-3xl md:text-4xl font-sans font-bold text-txt-primary tracking-tight font-sans-humanist">
              ₹0
            </p>
            <p className="text-[10px] font-sans font-bold text-success-text uppercase tracking-widest">
              Free Forever
            </p>
          </div>
        </div>
      </section>

      {/* 4. Categories Grid */}
      <section className="w-full relative py-20 px-6 border-t border-border-subt select-none">
        <div className="max-w-5xl mx-auto space-y-12">
          <div className="text-center space-y-3">
            <h2 className="font-display text-4xl md:text-5xl text-txt-primary">
              Learn Specific Code Smells
            </h2>
            <p className="text-sm text-txt-secondary max-w-md mx-auto font-sans-humanist tracking-wide">
              Our challenges are divided into seven category patterns commonly produced by generative AI models.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {categoryInfos.map((cat) => {
              const IconComponent = cat.icon;
              return (
                <Link
                  key={cat.id}
                  href={`/challenges?category=${cat.id}`}
                  className="group p-8 border border-border-subt bg-surface-card rounded-lg hover:border-border-def hover:[box-shadow:var(--shadow-soft)] transition-all duration-200 flex flex-col gap-6 text-left"
                >
                  <div className={`p-2.5 rounded-md border w-fit ${cat.color}`}>
                    <IconComponent className="w-5 h-5" />
                  </div>
                  <div className="space-y-2">
                    <h3 className="text-sm font-sans font-bold text-txt-primary group-hover:text-txt-primary transition-colors tracking-tight">
                      {cat.title}
                    </h3>
                    <p className="text-xs text-txt-secondary leading-relaxed font-sans-humanist">
                      {cat.description}
                    </p>
                  </div>
                </Link>
              );
            })}
          </div>
        </div>
      </section>
    </div>
  );
}
