import { SiteHeader } from "@/components/marketing/site-header";
import { SiteFooter } from "@/components/marketing/site-footer";

export const metadata = {
  title: "Terms of service: ReviewLabs",
  description: "The terms that cover using ReviewLabs.",
};

export default function TermsPage() {
  return (
    <>
      <SiteHeader />
      <main className="flex-1 px-6 py-16">
        <div className="mx-auto max-w-[720px]">
          <h1 className="text-display-md text-wise-ink">Terms of service</h1>
          <p className="mt-2 text-sm text-wise-mute">Last updated: October 1, 2026</p>
          <p className="mt-6 rounded-xl bg-wise-warning p-4 text-sm text-wise-warning-content">
            This is a draft written for ReviewLabs&apos;s current product. It has not yet been
            reviewed by a lawyer, and should get that review before the product handles real
            customer data at scale.
          </p>

          <div className="mt-8 flex flex-col gap-8 text-wise-body">
            <section>
              <h2 className="text-lg font-bold text-wise-ink">What ReviewLabs is</h2>
              <p className="mt-2">
                ReviewLabs helps a business collect customer ratings, catch unhappy customers
                privately before they post in public, and draft replies to Google reviews. By
                creating an account, you agree to these terms.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-wise-ink">Who can sign up</h2>
              <p className="mt-2">
                You need to be authorized to act for the business you&apos;re setting up,
                whether that&apos;s your own business or a client you manage on an agency plan.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-wise-ink">Plans and billing</h2>
              <p className="mt-2">
                Plans are billed monthly through Razorpay and you can cancel anytime; there&apos;s
                no annual contract requirement. Yearly plans, where offered, are billed upfront
                for the year. Prices are listed on the pricing page and can change with 30
                days&apos; notice to existing subscribers.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-wise-ink">Using the review tools responsibly</h2>
              <p className="mt-2">ReviewLabs is built around a few rules that apply to every account:</p>
              <ul className="mt-2 list-disc pl-5">
                <li>Don&apos;t hide the Google review option from a customer because they rated you low.</li>
                <li>Don&apos;t write or edit a review on a customer&apos;s behalf.</li>
                <li>Don&apos;t offer a customer a reward in exchange for a review.</li>
                <li>Don&apos;t hide low ratings on your public review page.</li>
              </ul>
              <p className="mt-2">
                These match Google&apos;s own policies on review gating and AI-written reviews.
                An account that violates them may be suspended.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-wise-ink">Connecting Google Business Profile</h2>
              <p className="mt-2">
                Connecting Google is optional. If you connect it, you&apos;re also bound by
                Google&apos;s own API terms for that connection. You can disconnect it from
                Settings at any time; ReviewLabs stops syncing and publishing replies
                immediately.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-wise-ink">AI-drafted replies</h2>
              <p className="mt-2">
                Reply drafts are generated by third-party AI providers and are a starting
                point, not a final answer. You&apos;re responsible for reviewing a draft before
                it publishes, except for the specific auto-reply case you turn on yourself (5-
                star reviews with no text). ReviewLabs isn&apos;t responsible for the content of
                a reply you chose to publish.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-wise-ink">Service availability</h2>
              <p className="mt-2">
                ReviewLabs is provided as is, without a guarantee that it will be uninterrupted
                or error-free. Google, AI provider, or payment provider outages outside our
                control can affect specific features.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-wise-ink">Ending an account</h2>
              <p className="mt-2">
                You can cancel your subscription at any time from Billing. We can suspend or
                end an account that violates these terms, the review-gating rules above, or
                Google&apos;s policies.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-wise-ink">Changes to these terms</h2>
              <p className="mt-2">
                If these terms change in a way that matters, we&apos;ll email account owners
                before the change takes effect.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-wise-ink">Governing law</h2>
              <p className="mt-2">These terms are governed by the laws of India.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-wise-ink">Contact</h2>
              <p className="mt-2">
                Questions about these terms: legal@reviewlabs.space (placeholder, set this up
                once the domain is live).
              </p>
            </section>
          </div>
        </div>
      </main>
      <SiteFooter />
    </>
  );
}
